name: Build

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install go-bindata
      run: go get -u github.com/go-bindata/go-bindata/...
      continue-on-error: true
    - name: Compiling src folder to go file
      run: go-bindata -nomemcopy src
    - name: Build
      run: go build -ldflags "-H=windowsgui"
    - name: Upload
      uses: actions/upload-artifact@v3.1.1
      with:
        name: rblx-rich-presence.exe
        path: ./rblx-richpresence.exe
