name: Git linter
on: [push, pull_request]
jobs:
  gitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        # checkout code before linting
        uses: actions/checkout@v2
        with:
          # fetch 20 commits (increase if needed)
          fetch-depth: '1'
      - name: Lint
        # run linter (use latest version here)
        uses: g4s8/gitlint-action@0.2
        with:
          pattern: (?<type>build)(?<scope>(?:\([^()\r\n]*\)|\()?(?<breaking>!)?)(?<subject>:.*)?
